CREATE TABLE [dbo].[Users]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[UserName] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(64) NOT NULL,
	[NameFull] VARCHAR(200) NOT NULL,
	[Email] VARCHAR(150) NOT NULL,
	[Available] BIT NOT NULL DEFAULT '1'
)